/*
 * Copyright 2026 HelixIAM contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.helixiam.authorization.theme.render;

import io.helixiam.authorization.theme.BrandPanel;
import io.helixiam.authorization.theme.Theme;
import io.helixiam.authorization.theme.ThemeColor;
import io.helixiam.authorization.theme.ThemeColorMath;
import io.helixiam.authorization.theme.ThemeColors;
import io.helixiam.authorization.theme.ThemeDefaults;
import io.helixiam.authorization.theme.ThemeUrls;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.function.Function;
import java.util.regex.Pattern;

/**
 * Renders {@code /realms/{realm}/theme.css} from an effective theme (spec §2): the {@code --hx-*} custom properties —
 * light values in {@code :root}, dark values in a {@code prefers-color-scheme: dark} block — then {@code @font-face}
 * rules for the uploaded fonts the theme names, then the (already re-validated) custom CSS.
 *
 * <p>The variable names are the documented, versioned theming contract ({@value #CONTRACT_VERSION}); the base
 * stylesheets read every colour, font, radius and spacing value from them.
 *
 * <p>Every value is re-checked before it is printed (colours {@code #RRGGBB}, sizes in range, font names and asset
 * URLs in their safe character sets): stored rows are validated on write, so a value that fails here can only come
 * from a corrupted row, and it is replaced by the HelixIAM default rather than reaching the stylesheet.
 */
public final class ThemeCssRenderer {

    /** Version of the {@code --hx-*} variable contract. Bump only with a documented, breaking change. */
    public static final int CONTRACT_VERSION = 1;

    /** Colour role → variable name (without the {@code --hx-} prefix). */
    public static final Map<String, String> COLOR_VARIABLES = colorVariables();

    /** The HelixIAM default sans (bundled Work Sans; its {@code @font-face} lives in the base stylesheet). */
    static final String SYSTEM_SANS = "system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif";
    static final String SYSTEM_SERIF = "ui-serif, Georgia, Cambria, \"Times New Roman\", Times, serif";
    static final String SYSTEM_MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace";
    static final String HELIX_SANS = "\"Work Sans\", " + SYSTEM_SANS;
    static final String MONO = "\"Roboto Mono\", " + SYSTEM_MONO;

    private static final Map<String, String> BUILT_IN_STACKS = Map.of(
            "helix-sans", HELIX_SANS,
            "system-sans", SYSTEM_SANS,
            "system-serif", SYSTEM_SERIF,
            "system-mono", SYSTEM_MONO);

    // Same character set as the upload rules and ThemeValidator.FONT_NAME: safe inside a double-quoted CSS string.
    private static final Pattern FONT_NAME = Pattern.compile("[A-Za-z0-9][A-Za-z0-9 _.-]{0,63}");
    private static final Pattern WEIGHT = Pattern.compile("[1-9][0-9]{0,2}( [1-9][0-9]{0,2})?");
    private static final Pattern STYLE = Pattern.compile("normal|italic");

    private ThemeCssRenderer() {
    }

    /**
     * The stylesheet for {@code theme}, which must be an effective theme (all layers merged, dark values derived).
     *
     * @param fonts the realm's uploaded font files; only those of a family the theme names are emitted
     */
    public static String render(final Theme theme, final List<FontFace> fonts) {
        final ThemeColors colors = theme.colors() == null ? ThemeDefaults.THEME.colors() : theme.colors();
        final Function<String, String> light = role -> color(colors, role, true);
        final Function<String, String> dark = role -> color(colors, role, false);
        final String fontSans = fontName(theme.typography() == null ? null : theme.typography().fontSans(),
                ThemeDefaults.THEME.typography().fontSans());
        final String fontDisplay = fontName(theme.typography() == null ? null : theme.typography().fontDisplay(),
                ThemeDefaults.THEME.typography().fontDisplay());

        final StringBuilder css = new StringBuilder(2048);
        css.append("/* Generated by HelixIAM from the realm theme. Theming contract v").append(CONTRACT_VERSION)
                .append(" (--hx-* custom properties). */\n");
        css.append(":root {\n");
        css.append("  color-scheme: light dark;\n");
        colorBlock(css, light, "  ");
        // Text on primary is surfaceRaised: the pair the validator checks for WCAG AA contrast.
        prop(css, "  ", "on-primary", light.apply("surfaceRaised"));
        // The split layout's brand panel inverts the page: ink ground, surface text, the light-on-dark primary.
        final ThemeColors safe = ThemeColors.from(role -> new ThemeColor(light.apply(role), dark.apply(role)));
        final BrandPanel.Colors lightPanel = BrandPanel.light(safe);
        prop(css, "  ", "brand-bg", lightPanel.background());
        prop(css, "  ", "brand-fg", lightPanel.foreground());
        prop(css, "  ", "brand-accent", lightPanel.accent());
        prop(css, "  ", "font-sans", stack(fontSans));
        prop(css, "  ", "font-display", stack(fontDisplay));
        prop(css, "  ", "font-display-weight", String.valueOf(displayWeight(fontDisplay)));
        prop(css, "  ", "font-display-tracking", serifLike(fontDisplay) ? "-0.005em" : "-0.02em");
        prop(css, "  ", "font-mono", MONO);
        prop(css, "  ", "font-size", baseSize(theme) + "px");
        prop(css, "  ", "radius", radius(theme) + "px");
        prop(css, "  ", "space", ("compact".equals(density(theme)) ? 3 : 4) + "px");
        css.append("}\n");

        css.append("@media (prefers-color-scheme: dark) {\n  :root {\n");
        colorBlock(css, dark, "    ");
        prop(css, "    ", "on-primary", dark.apply("surfaceRaised"));
        final BrandPanel.Colors darkPanel = BrandPanel.dark(safe);
        prop(css, "    ", "brand-bg", darkPanel.background());
        prop(css, "    ", "brand-fg", darkPanel.foreground());
        prop(css, "    ", "brand-accent", darkPanel.accent());
        css.append("  }\n}\n");

        for (final FontFace face : fonts == null ? List.<FontFace>of() : fonts) {
            if (face == null || !(face.family().equals(fontSans) || face.family().equals(fontDisplay))
                    || !validFace(face)) {
                continue;
            }
            css.append("@font-face {\n")
                    .append("  font-family: \"").append(face.family()).append("\";\n")
                    .append("  src: url(\"").append(face.url()).append("\") format(\"woff2\");\n")
                    .append("  font-weight: ").append(face.weight()).append(";\n")
                    .append("  font-style: ").append(face.style()).append(";\n")
                    .append("  font-display: swap;\n")
                    .append("}\n");
        }

        final String custom = theme.customCss();
        if (custom != null && !custom.isBlank() && servable(custom)) {
            css.append("/* Custom CSS (escape hatch; depends on internal markup) */\n").append(custom.strip()).append('\n');
        }
        return css.toString();
    }

    /** The CSS value of a font setting: a built-in stack, or an uploaded family followed by the system sans stack. */
    static String stack(final String font) {
        final String builtIn = BUILT_IN_STACKS.get(font);
        return builtIn != null ? builtIn : "\"" + font + "\", " + SYSTEM_SANS;
    }

    /**
     * The heading weight for a display font: 800 for the bundled Work Sans (the built-in look), 700 for other sans
     * faces, 600 for serif and mono faces (a heavy serif at 800 is dense). Uploaded families are classified by name.
     */
    static int displayWeight(final String font) {
        if ("helix-sans".equals(font)) {
            return 800;
        }
        return serifLike(font) ? 600 : 700;
    }

    static boolean serifLike(final String font) {
        final String f = font == null ? "" : font.toLowerCase(Locale.ROOT);
        return "system-serif".equals(f) || "system-mono".equals(f)
                || (f.contains("serif") && !f.contains("sans")) || f.contains("mono");
    }

    private static void colorBlock(final StringBuilder css, final Function<String, String> value, final String indent) {
        COLOR_VARIABLES.forEach((role, name) -> prop(css, indent, name, value.apply(role)));
    }

    private static void prop(final StringBuilder css, final String indent, final String name, final String value) {
        css.append(indent).append("--hx-").append(name).append(": ").append(value).append(";\n");
    }

    private static String color(final ThemeColors colors, final String role, final boolean light) {
        final ThemeColor c = colors.role(role);
        final String v = c == null ? null : light ? c.light() : c.dark();
        if (v != null && ThemeColorMath.isHex(v)) {
            return v.toLowerCase(Locale.ROOT);
        }
        final ThemeColor fallback = ThemeDefaults.THEME.colors().role(role);
        return light ? fallback.light() : fallback.dark();
    }

    private static String fontName(final String font, final String fallback) {
        if (font != null && (BUILT_IN_STACKS.containsKey(font) || FONT_NAME.matcher(font).matches())) {
            return font;
        }
        return fallback;
    }

    private static boolean validFace(final FontFace face) {
        return face.family() != null && FONT_NAME.matcher(face.family()).matches()
                && !BUILT_IN_STACKS.containsKey(face.family())
                && ThemeUrls.parseAsset(face.url()).filter(a -> "woff2".equals(a.extension())).isPresent()
                && face.weight() != null && WEIGHT.matcher(face.weight()).matches()
                && face.style() != null && STYLE.matcher(face.style()).matches();
    }

    private static int baseSize(final Theme theme) {
        final Integer v = theme.typography() == null ? null : theme.typography().baseSize();
        return v != null && v >= 14 && v <= 18 ? v : ThemeDefaults.THEME.typography().baseSize();
    }

    private static int radius(final Theme theme) {
        final Integer v = theme.shape() == null ? null : theme.shape().radius();
        return v != null && v >= 0 && v <= 16 ? v : ThemeDefaults.THEME.shape().radius();
    }

    private static String density(final Theme theme) {
        final String v = theme.shape() == null ? null : theme.shape().density();
        return "compact".equals(v) || "comfortable".equals(v) ? v : ThemeDefaults.THEME.shape().density();
    }

    /**
     * Last line of defence for the custom CSS: the effective theme only carries CSS that passed the full validator
     * (with the realm's allowlist), so this only re-checks the constructs that could break out of the stylesheet or
     * run script, whatever the allowlist.
     */
    private static boolean servable(final String css) {
        return css.indexOf('<') < 0 && css.indexOf('\\') < 0 && !css.contains("/*")
                && !css.toLowerCase(Locale.ROOT).contains("@import")
                && !css.toLowerCase(Locale.ROOT).contains("javascript:")
                && !css.toLowerCase(Locale.ROOT).contains("expression(");
    }

    private static Map<String, String> colorVariables() {
        final Map<String, String> out = new LinkedHashMap<>();
        for (final String role : ThemeColors.ROLES) {
            out.put(role, role.replaceAll("([A-Z])", "-$1").toLowerCase(Locale.ROOT));
        }
        return java.util.Collections.unmodifiableMap(out);
    }
}
